### ISSUE TITLE
State TLS compatibility

### ISSUE THREAD

**Issue by lnksz** [cesanta/mongoose#1198]
Hi There,

from your `test.yaml` it is not stable/deterministic to which versions of mbedtls and openssl are you tested/compatible with.

This info would be great so that one can see dependency-compatibility transparently.

```yml
  linux:
    runs-on: ubuntu-latest  # <== moving target
    steps:
    - uses: actions/checkout@v2
    - name: Install packages
      run: sudo apt-get install libmbedtls-dev
    - name: make
      run: make test test++ IPV6=0
    - name: openssl
      run: make test SSL=OPENSSL IPV6=0
```
mbedtls has 3 relevant branches:
- 2.x bleeding edge
- 2.16 new LTS
- 2.7.x old LTS although this has an EOL in 2021-February
- upcoming v3...

openssl:
- 1.1.1* although I do not know how much of a difference the sub-versions make
- 1.0.1 EOL : a (non-)support statement about it would be beneficent.

I think a section about TLS compatibility in your README/Doc would be great.
